### PR TITLE
Avoid rate limiting by using GitHub token

### LINKED ISSUE #65: Use GitHub token to avoid rate limiting
A job failed because of this error. Initial investigation seems to suggest it is coming from [tool-cache](https://github.com/actions/toolkit/blob/main/packages/tool-cache/src/tool-cache.ts)

https://github.com/nvm-sh/nvm/runs/4919179993?check_suite_focus=true#step:2:5

### PR DESCRIPTION
**Pull request by Devils-Knight**
Fixes #65

### CODE REVIEW

**Comment by varunsh-coder** [comment]
@Devils-Knight you also need to update `action.yml` to add token and set default to github token.

File: src/setup.ts [hunk 1]
```diff
@@ -19,6 +19,8 @@ import {verifyChecksum} from "./checksum"
     var api_url = `https://${env}.api.stepsecurity.io/v1`;
     var web_url = "https://app.stepsecurity.io";
 
+    let token = core.getInput('token');
```
Comment (varunsh-coder) [inline src/setup.ts:22]: @Devils-Knight please add a comment that this is to avoid rate limit

Comment (Devils-Knight) [reply src/setup.ts:22]: @varunsh-coder added comment and updated the inputs for `action.yml`.
